SELECT
N,
CASE
    WHEN (SELECT COUNT(*) FROM BST AS tmp1 WHERE tmp1.N = BST.N AND tmp1.P IS NULL) > 0 THEN 'Root'
    WHEN (SELECT COUNT(*) FROM BST AS tmp1 WHERE tmp1.P = BST.N) > 0 THEN 'Inner'
    ELSE 'Leaf'
END
FROM
BST
ORDER BY N